---
- hosts: all
  become: yes
  
  pre_tasks:
    - name: Install needed ansible dconf dependency
      package:
        state: present
        name: python3-psutil
    - name: Install other needed dependencies
      package:
        state: present
        name:
          - git

  tasks:
    - name: Update apt repo and cache
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      apt:
        upgrade: dist
        force_apt_get: yes

    - name: Remove dependencies that are no longer required
      apt:
        autoremove: yes

    - name: AWS CLI (OS bundled) removed
      package:
        name: aws-cli
        state: absent

    - name: AWS CLI - Download and Extract latest
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/
        remote_src: yes
        mode: 0500

    - name: AWS CLI - Install system wide
      command: /tmp/aws/install --update

    - name: Useful tools and packages
      package:
        state: present
        name:
          - htop
          - chromium-browser

    - user:
        name: rbeede
        password: ""

    - authorized_key:
        user: rbeede
        state: present
        key: https://github.com/rbeede.keys

    - name: Terminal font size
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
        value: '"Monospace 18"'
      become_user: rbeede

    - name: Terminal font size use custom
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font"
        value: "false"
      become_user: rbeede

    - name: Terminal don't use theme colors
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-theme-colors"
        value: "false"
      become_user: rbeede

    - name: Terminal background-color
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-color"
        value: '"rgb(0,0,0)"'
      become_user: rbeede

    - name: Terminal font color
      dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/foreground-color"
        value: '"rgb(0,255,0)"'
      become_user: rbeede
      
    - name: Disable screen lock
      dconf:
        key: "/org/gnome/desktop/screensaver/lock-enabled"
        value: "false"
      become_user: rbeede
      
    - name: Disable lock on suspend
      dconf:
        key: "/org/gnome/desktop/screensaver/ubuntu-lock-on-suspend"
        value: "false"
      become_user: rbeede

    - name: Setup launcher favorites
      dconf:
        key: "/org/gnome/shell/favorite-apps"
        value: "['firefox.desktop', 'org.gnome.Nautilus.desktop', 'chromium_chromium.desktop', 'org.gnome.Terminal.desktop']"
      become_user: rbeede

    - name: Burp configuration directory
      file:
        path: /home/rbeede/.BurpSuite
        group: rbeede
        owner: rbeede
        mode: 0700
        state: directory
      
    - name: Burp user settings file
      copy:
        src: UserConfigPro.json
        dest: /home/rbeede/.BurpSuite/UserConfigPro.json
        mode: 0600
        owner: rbeede


    - name: Reboot forcefully after all done
      command: /sbin/reboot
