- import_tasks: setup_authentication.yml

- import_tasks: setup_home_files.yml

- import_tasks: setup_desktop_settings.yml
  tags: [ never, gui ]

- import_tasks: install_google_chrome.yml
  tags: [ never, gui ]
