- name: Mozilla Repo Signing Key
  ansible.builtin.get_url:
    url: https://packages.mozilla.org/apt/repo-signing-key.gpg
    dest: /etc/apt/keyrings/packages.mozilla.org.apt.repo-signing-key.asc
    mode: '0444'

- name: Apt Sources
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/mozilla.list
    content: "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.apt.repo-signing-key.asc] https://packages.mozilla.org/apt mozilla main\n"
    owner: root
    group: root
    mode: '0444'

- name: Prefer Mozilla Deb
  ansible.builtin.copy:
    dest: /etc/apt/preferences.d/mozilla
    content: |
      Package: *
      Pin: origin packages.mozilla.org
      Pin-Priority: 1000
    owner: root
    group: root
    mode: '0444'

- name: Remove old apt linked to snap view of firefox
  ansible.builtin.apt:
    state: absent
    name: "firefox"

- name: Update apt repo and cache forcing apt policy to update for firefox
  ansible.builtin.apt:
    clean: true
    update_cache: yes
    force_apt_get: yes
    allow_downgrade: yes
    cache_valid_time: 0

- name: Force apt to install Firefox and not snap
  ansible.builtin.apt:
    state: present
    name: "firefox"
