- name: Update apt repo and cache
  apt:
    update_cache: yes
    force_apt_get: yes
    cache_valid_time: 3600

# At this point do NOT apply all system updates as that can crash the current session and cause later ansible tasks to fail


- name: Remove unneeded packages
  package:
    state: absent
    name: "{{ packages_to_uninstall }}"

- name: Remove unwanted snaps
  community.general.snap:
    name:
      - bare
      - core22
      - firefox
      - firmware-updater
      - gnome-42-2204
      - gtk-common-themes
      - snap-store
      - snapd
      - snapd-desktop-integration
      - thunderbird
    state: absent

- name: Remove unneeded snap
  package:
    state: absent
    name: "snapd"

- name: Build list of packages to install
  set_fact:
    packages_to_install: "{{ useful_tools_headless }}"

- name: Build list of packages to install if gui
  set_fact:
    packages_to_install: "{{ packages_to_install + useful_tools_gui }}"
  tags: [ never, gui ]

- name: Useful tools and packages
  package:
    state: present
    name: "{{ packages_to_install }}"

- name: Software tools directory
  file:
    path: /Software
    owner: rbeede
    group: rbeede
    mode: 0700
    state: directory
  
- name: Handy shell scripts
  copy:
    src: Software/  # from role's files/ directory
    dest: /Software/
    owner: rbeede
    group: rbeede
    mode: 0500

- name: Deb Firefox not snap
  import_tasks: firefox_deb.yml
  tags: [ never, gui ]

- name: Firefox settings
  import_tasks: firefox_user_prefs.yml
  tags: [ never, gui ]
